language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool autotools-dev autoconf pkg-config libssl-dev libminiupnpc-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev libevent-dev
script:
  - ./autogen.sh
  - ./configure
  - make -s -l 2.5 -j 4
before_deploy:
#- true
#- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#- git tag $TRAVIS_TAG
  - mkdir $TRAVIS_BUILD_DIR/deploy
  - cp $TRAVIS_BUILD_DIR/src/bulwark-cli $TRAVIS_BUILD_DIR/src/bulwark-tx
    $TRAVIS_BUILD_DIR/src/bulwarkd $TRAVIS_BUILD_DIR/deploy
  - strip --strip-debug $TRAVIS_BUILD_DIR/deploy/*
  - cd $TRAVIS_BUILD_DIR/deploy
  - tar -zvcf bulwark-bin.tar.gz *
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/deploy/bulwark-bin.tar.gz
  overwrite: true
  skip_cleanup: true
  #draft: true
  name: ${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  tag_name: ${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  on:
    repo: cryptocrowd-xcrc/xcrc-wallet
    branch: travisci-headless
    tags: false #true
