language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool autotools-dev autoconf pkg-config libssl-dev libminiupnpc-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev libevent-dev
script:
  - ./autogen.sh
  - ./configure
  - make -s -l 2.5 -j 4
before_deploy:
- true
- cd ..
- tar -zvcf bulwark-bin.tar.gz bin/
- echo `pwd`
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: bulwark-*
  overwrite: true
  skip_cleanup: true
  #draft: true
  on:
    repo: cryptocrowd-xcrc/xcrc-wallet
    branch: travisci-headless
    tags: false
