language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:bitcoin/bitcoin
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libtool autotools-dev autoconf pkg-config libssl-dev libminiupnpc-dev libboost-all-dev
script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
